#ifndef __ERROR_H__
#define __ERROR_H__

#define OS_NO_ERROR								0000

// os error
#define OS_FUNCTION_ARGS_ERROR 	 				1001
#define OS_FRAME_TYPE_ERROR    	 				1002
#define OS_CREATE_THREAD_ERROR	 				1003
#define OS_CREATE_EPOLL_ERROR	 				1004
#define OS_EPOLL_ADD_EVENT_ERROR 				1005
#define OS_EPOLL_DEL_EVENT_ERROR 				1006
#define OS_NOT_INIT_ERROR		 				1007
#define OS_REPEAT_INIT_ERROR	 				1008
#define OS_CREATE_RTP_INSTANCE_HANDLER_ERROR	1009
#define OS_NOT_FIND_RTP_INSTANCE				1010
#define OS_RECV_MEDIA_DATA_CB_EMPTY				1011
#define OS_NOT_FIND_PS_PACKET					1012
#define OS_NOT_FIND_VALID_RTP_PACKET			1013
#define OS_NOT_SET_SDK_MODEL					1014
#define OS_TRANS_PROTOCOL_TYPE_ERROR			1015
#define OS_STREAM_TYPE_ERROR					1016 
#define OS_NOT_INIT_OBJECT						1017
#define OS_PACKET_TYPE_ERROR					1018
#define OS_HANDLER_NOT_INIT						1019

// log error
#define LOG_CREATE_LOG_FILE_ERROR 				1101
#define LOG_FILE_NAME_ERROR						1102
#define LOG_GET_HEADER_ERROR 					1103
#define LOG_CONVERT_CALENDAR_TIME_ERROR 		1104
#define LOG_GET_TIME_OF_DAY_ERROR 				1105
#define LOG_INIT_ERROR							1106
#define LOG_LEVEL_NOT_AVAILABLE					1107
#define LOG_FILE_NAME_ERROR						1108
#define LOG_LEVEL_ERROR							1109

// socket error
#define SOCKET_CONNECTION_ERROR      			1201
#define SOCKET_CONNECTION_OK 	     			1202
#define SOCKET_CONNECT_SERVER_FAILED 			1203
#define SOCKET_BIND_ERROR						1204
#define SOCKET_LISTEN_ERROR						1205
// rtp error
#define WRITE_FRAME_DATA_ERROR					1301
#define RTP_ARRAY_FULL_ERROR					1302
#define NOT_FIND_FRAME_ERROR					1303
#endif
